import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ptBR } from '@clerk/localizations';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider
      localization={ptBR}
    // appearance={{ baseTheme: neobrutalism }} 
    >
      <html lang="pt-Br">
        <body
        // className={inter.className}
        >
          {children}
        </body>
      </html>
    </ClerkProvider >
  )
}
